// <auto-generated />
using System;
using CM4_DataAccess.DBV1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CM4_DataAccess.Migrations
{
    [DbContext(typeof(WorldContext))]
    [Migration("20250111215236_OrgCharManyToMany")]
    partial class OrgCharManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CM4_Core.Models.Character", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("CM4_Core.Models.Organization", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrganizationID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("OrganizationID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("CharacterOrganization", b =>
                {
                    b.Property<Guid>("MembersID")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MembershipsID")
                        .HasColumnType("TEXT");

                    b.HasKey("MembersID", "MembershipsID");

                    b.HasIndex("MembershipsID");

                    b.ToTable("CharacterOrganization");
                });

            modelBuilder.Entity("CM4_Core.Models.Organization", b =>
                {
                    b.HasOne("CM4_Core.Models.Organization", null)
                        .WithMany("MemberOrgs")
                        .HasForeignKey("OrganizationID");
                });

            modelBuilder.Entity("CharacterOrganization", b =>
                {
                    b.HasOne("CM4_Core.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("MembersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CM4_Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("MembershipsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CM4_Core.Models.Organization", b =>
                {
                    b.Navigation("MemberOrgs");
                });
#pragma warning restore 612, 618
        }
    }
}
